name: PrecompiledShaderPipeline macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        repository: electronicarts/EASTL
        token: ${{ secrets.MINIMAL_PAT }}
        path: submodules/eastl
        ref: master

    - name: Build and install
      run: |
        git config --global url."https://github.com/".insteadOf git@github.com:
        git config --global url."https://".insteadOf git://
        sh cso-install-required-python.sh
        sh cso-macos-xcode-build-install.sh
        sh cso-update-binaries-macos.sh

    - name: Run tests
      run: |
        sh cso-run-all-tests.sh

